"""Concatenate a rung into ONE Kaggle script-kernel file.

Script kernels upload code_file ONLY (siblings are invisible), so all modules
are inlined. Intra-project imports are stripped (names share one namespace
after concat); everything else (stdlib) is kept. Colliding top-level names
across files are an authoring error -> build fails loudly.

Usage: python3 tools/build_kernel.py kaggle/exp04/manifest.txt kaggle/exp04/kernel.py
Manifest: one source path per line, '#' comments, relative to repo root.
"""
import re
import sys
from pathlib import Path

STRIP_IMPORT = re.compile(
    r"^\s*(from\s+(tasks|loop|synth|cegis|sketch|run)\s+import\s+.*|"
    r"sys\.path\.insert.*|from\s+pathlib\s+import.*|import\s+sys\s*)$")


def build(manifest: Path, out: Path):
    root = Path(__file__).resolve().parents[1]
    parts = []
    seen_names = {}
    for line in manifest.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        src = root / line
        body = []
        for ln in src.read_text().splitlines():
            if STRIP_IMPORT.match(ln):
                continue
            body.append(ln)
        for i, ln in enumerate(body):
            m = re.match(r"^(def|class)\s+(\w+)", ln)
            if m:
                kind, name = m.groups()
                if name in seen_names and name != "main":
                    raise SystemExit(
                        f"collision: {kind} {name} in {line} "
                        f"already defined by {seen_names[name]}")
                seen_names[name] = line
        parts.append(f"\n# ===== {line} =====\n" + "\n".join(body))
    header = ('# GENERATED by tools/build_kernel.py — do not edit.\n'
              '# Single-file Kaggle script kernel (siblings are not uploaded).\n'
              'import argparse, json, sys, time\n'
              'from pathlib import Path\n')
    out.write_text(header + "\n".join(parts) + "\n")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    build(Path(sys.argv[1]), Path(sys.argv[2]))
